// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRKRRcT7QhzpVqcM8b0Qpkfw5awxSsSVA',
    appId: '1:869817381049:web:dbdd2a1fd6d490565e6b68',
    messagingSenderId: '869817381049',
    projectId: 'pdfreader-cf188',
    authDomain: 'pdfreader-cf188.firebaseapp.com',
    storageBucket: 'pdfreader-cf188.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXtbFxu0ErbElHbkhYYv62GdTht1HZ-IE',
    appId: '1:869817381049:android:08f96333eda23f615e6b68',
    messagingSenderId: '869817381049',
    projectId: 'pdfreader-cf188',
    storageBucket: 'pdfreader-cf188.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0_6ISRFdGB0MVCy4XW5iZpomcwoB4TSc',
    appId: '1:869817381049:ios:397ab3a9a31f3a2e5e6b68',
    messagingSenderId: '869817381049',
    projectId: 'pdfreader-cf188',
    storageBucket: 'pdfreader-cf188.firebasestorage.app',
    iosBundleId: 'com.example.pdfreader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0_6ISRFdGB0MVCy4XW5iZpomcwoB4TSc',
    appId: '1:869817381049:ios:397ab3a9a31f3a2e5e6b68',
    messagingSenderId: '869817381049',
    projectId: 'pdfreader-cf188',
    storageBucket: 'pdfreader-cf188.firebasestorage.app',
    iosBundleId: 'com.example.pdfreader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRKRRcT7QhzpVqcM8b0Qpkfw5awxSsSVA',
    appId: '1:869817381049:web:88d2eb85190987645e6b68',
    messagingSenderId: '869817381049',
    projectId: 'pdfreader-cf188',
    authDomain: 'pdfreader-cf188.firebaseapp.com',
    storageBucket: 'pdfreader-cf188.firebasestorage.app',
  );

}